# Site settings
title: Jeffrey M Johnson
email: JefJohMS@gmail.com
description: #>  this means to ignore newlines until "baseurl:"
  This site is a bag of holding for my adventure on the path of becoming an expert game developer.
  
  "People are reliably terrible at being reliable." - @munificentbob
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://JeffreyMJohnson.info" # the base hostname & protocol for your site
twitter_username: HoquiamJMJ
github_username:  JeffreyMJohnson

# Build settings
markdown: kramdown
